version: '3'
services:

  app:
    image: trafex/php-nginx
    #container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    networks:
      - app-network


#Docker Networks
networks:
  app-network:
    driver: bridge

