version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
#    image: php:8.1.8-fpm-alpine3.15
    build: .
    volumes:
      - ./:/code
